services:
  app:
    image: python:3.9
    command: >
      sh -c "pip3 install requests && 
             pip3 install schedule && 
             pip3 install psycopg2-binary && 
             pip3 install python-dotenv && 
             python3 scraperv2.py"
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./:/app
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

